### ISSUE TITLE
Release v1 - ToDo

### ISSUE THREAD

**Issue by romsahel** [romsahel/OfflineMdb#1]
# v1.0

- [x] Trim the search
- [x] Display a welcome text when no search result is visible (Offline Movie Database, provided by imdb.com)
- [x] Rename the app to OMDb
- [x] Create an icon for the app (and for the notification)

# v1.1
- [x] Use original title in search as well (so that french movies can be easily searched)
- [x] Display genres in search result
- [x] Check IMDb terms of conditions
